fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.13.1
    epel:
      repo: https://github.com/stahnma/puppet-module-epel.git
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      ref: 1.0.1
  symlinks:
    singularity: "#{source_dir}"
