---
.travis.yml:
  docker_sets:
    - set: centos-7
      collection: puppet5
    - set: centos-7
      collection: puppet6
    - set: centos-6
      collection: puppet5
    - set: centos-6
      collection: puppet6
  user: treydock
  secure: "E4xBofpdhqXW2qQEpzhkQfBi4+1lk59X2VtfgtINg1wD+/dbk5mQbDKYVrdbouhRws7GDn7E32W8SU/zHHkF7e8ce7G6GrFnlVRWMzcNtX91yreP9vJEa6VbRze1w8zeMyKWzc5TCVOJTG3lwU0Z+ul/90CJxRJyUCreiSWVObpLiYsj1zAikX6J13aynbpU1ycxsBB4+1BfrCojKQ/LtH0OC2Dnqso1f5VEXPdPvLFbsd7Z6suFWPJwWKsV51Vn+PWk6t7slch4J4aIOafEnuLOOD2E64XztoppckKGgdN8I0vP5sNeuNWvFrGszcxCdC1BolqDjXCwaVPLl3cWLw0J615K+Jt838Dprx7EkkTkG/f4guINdm2mewSPJMcualxJ+i0B09Qy2P/1pitcNiVQUUUmia3PX3zFKQPQmave7WVdIXdzbvMoWfugPWKoKedZNRBbDBw4t8pFuGccn9ZLXHsINM6bZv4qIOIKMaiqcCSFJEiJK0830B9rGyhKK2jUBp0eb/Df9prgAnPjdpvUEjGZiC/QlGb7EhysqMs2s3YsXZ62p5hgTpmQmFpk9irDWWRfvP/QJ6kOOZ0iQhmOBfFuvE820u8UeF/8awv0x8w+L/VF5wzjAkGr8PC4M0h8zVTDmFhbJz5kI48kHhvG9OsJurR1tPTguxpYmXw="
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1404.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
